x = input("Who's birthday is it?")
print( x + " is the birthday girl")
print ("Happy Birthday to you")
print ("Happy Birthday to you")
print ("Happy Birthday, dear" + x)
print ("Happy Birthday to you")